In [45]:
### NLP_Assign_6_Compare_Docs_Matrix.ipynb

In [46]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [47]:
import string
from collections import Counter
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import warnings
warnings.filterwarnings('ignore')

In [65]:
text = open(r'/content/drive/My Drive/NLP/edu_policy3_2020.txt', encoding="utf-8").read()
text2 = open(r'/content/drive/My Drive/NLP/edu_policy2_2020.txt', encoding="utf-8").read()

In [49]:
lower_case = text.lower()
lower_case

'the new education policy has a commendable vision, but its potency will depend on whether it is able to effectively integrate with the government’s other policy initiatives.\nindia introduced its new national education policy (nep) 2020 last week, laying out the narendra modi government’s vision and broad direction conceived for educational reform. it was considerably overdue — the nep is only india’s third education policy document; the previous one was revised in 1992. the policy introduces a whole gamut of changes and reads as a very progressive document overall, with a firm grasp on the current socio-economic landscape and the prospect of future uncertainty. education for a new generation of learners has to necessarily engage with the increasing dematerialisation and digitalisation of our economies, requiring a completely new set of capabilities in order to be able to keep up. this seems to be an even more urgent prerogative now, with the trend towards digitalisation and disruptiv

In [77]:
lower_case2 = text2.lower()
lower_case2

'29 july, 2020 is going to be an important day for indian education system, as the government decided to bring in national education policy (nep) with a long term vision of making india a global knowledge superpower with a focus on inclusiveness, participation and holistic approach. nep 2020 is third in series since independence; the first two were introduced in 1968 and 1986 respectively. it is based on the pillars of access, equity, quality, affordability, and accountability. this article will focus more on the vision plan made for higher education and potentials risks ahead. risks can be managed well, only if identified correctly and at the right time. \n\nthe new policy is expected to bring positive and long-lasting changes in the indian higher education system. several innovative ideas have been considered while formulating this policy to improve effectiveness and finally achieve its long term goal. there are some really great steps planned within the policy ambit for taking the i

In [50]:
# make a dictionary of Contractions

contraction_mapping={
"ain't": "is not",
"aren't": "are not",
"can't": "cannot",
"can't've": "cannot have",
"'cause": "because",
"could've": "could have",
"couldn't": "could not",
"couldn't've": "could not have",
"didn't": "did not",
"doesn't": "does not",
"don't": "do not",
"hadn't": "had not",
"hadn't've": "had not have",
"hasn't": "has not",
"haven't": "have not",
"he'd": "he would",
"he'd've": "he would have",
"he'll": "he will",
"he'll've": "he he will have",
"he's": "he is",
"how'd": "how did",
"how'd'y": "how do you",
"how'll": "how will",
"how's": "how is",
"I'd": "I would",
"I'd've": "I would have",
"I'll": "I will",
"I'll've": "I will have",
"I'm": "I am",
"I've": "I have",
"i'd": "i would",
"i'd've": "i would have",
"i'll": "i will",
"i'll've": "i will have",
"i'm": "i am",
"i've": "i have",
"isn't": "is not",
"it'd": "it would",
"it'd've": "it would have",
"it'll": "it will",
"it'll've": "it will have",
"it's": "it is",
"let's": "let us",
"ma'am": "madam",
"mayn't": "may not",
"might've": "might have",
"mightn't": "might not",
"mightn't've": "might not have",
"must've": "must have",
"mustn't": "must not",
"mustn't've": "must not have",
"needn't": "need not",
"needn't've": "need not have",
"o'clock": "of the clock",
"oughtn't": "ought not",
"oughtn't've": "ought not have",
"shan't": "shall not",
"sha'n't": "shall not",
"shan't've": "shall not have",
"she'd": "she would",
"she'd've": "she would have",
"she'll": "she will",
"she'll've": "she will have",
"she's": "she is",
"should've": "should have",
"shouldn't": "should not",
"shouldn't've": "should not have",
"so've": "so have",
"so's": "so as",
"that'd": "that would",
"that'd've": "that would have",
"that's": "that is",
"there'd": "there would",
"there'd've": "there would have",
"there's": "there is",
"they'd": "they would",
"they'd've": "they would have",
"they'll": "they will",
"they'll've": "they will have",
"they're": "they are",
"they've": "they have",
"to've": "to have",
"wasn't": "was not",
"we'd": "we would",
"we'd've": "we would have",
"we'll": "we will",
"we'll've": "we will have",
"we're": "we are",
"we've": "we have",
"weren't": "were not",
"what'll": "what will",
"what'll've": "what will have",
"what're": "what are",
"what's": "what is",
"what've": "what have",
"when's": "when is",
"when've": "when have",
"where'd": "where did",
"where's": "where is",
"where've": "where have",
"who'll": "who will",
"who'll've": "who will have",
"who's": "who is",
"who've": "who have",
"why's": "why is",
"why've": "why have",
"will've": "will have",
"won't": "will not",
"won't've": "will not have",
"would've": "would have",
"wouldn't": "would not",
"wouldn't've": "would not have",
"y'all": "you all",
"y'all'd": "you all would",
"y'all'd've": "you all would have",
"y'all're": "you all are",
"y'all've": "you all have",
"you'd": "you would",
"you'd've": "you would have",
"you'll": "you will",
"you'll've": "you will have",
"you're": "you are",
"you've": "you have"
}

In [51]:
# function to pre-process the text
def cleaner(text):
    newString=re.sub(r"@[a-zA-Z0-9]+","",text)         # removing user mentions
    newString=re.sub("#","",newString) 
    newString=' '.join([contraction_mapping[t] if t in contraction_mapping else t for t in newString.split(" ")])
    x=re.sub(r'http\S+','',newString)                  # remove URL's
    newString=re.sub(r"'s\b"," is",newString)         # removing 's
    x=re.sub(r'[%#@$&!+|Ÿð¦±]','',newString)          # Remove spacial char
    x=re.sub(r'[.,:;]','',newString)                   # remove punctuations mark
    newString=re.sub("[^a-zA-Z]"," ",newString)         # fetching out only char
    #lower_case=letters_only.lower()                     # converting everything in lowercase
    words=newString.split()                            # split based on space to remove multiple spaces
    return (" ".join(words)).strip()

In [52]:
cleaned_text = cleaner(lower_case)
cleaned_text

'the new education policy has a commendable vision but its potency will depend on whether it is able to effectively integrate with the government s other policy initiatives india introduced its new national education policy nep last week laying out the narendra modi government s vision and broad direction conceived for educational reform it was considerably overdue the nep is only india s third education policy document the previous one was revised in the policy introduces a whole gamut of changes and reads as a very progressive document overall with a firm grasp on the current socio economic landscape and the prospect of future uncertainty education for a new generation of learners has to necessarily engage with the increasing dematerialisation and digitalisation of our economies requiring a completely new set of capabilities in order to be able to keep up this seems to be an even more urgent prerogative now with the trend towards digitalisation and disruptive automation being acceler

In [78]:
cleaned_text2 = cleaner(lower_case2)
cleaned_text2

'july is going to be an important day for indian education system as the government decided to bring in national education policy nep with a long term vision of making india a global knowledge superpower with a focus on inclusiveness participation and holistic approach nep is third in series since independence the first two were introduced in and respectively it is based on the pillars of access equity quality affordability and accountability this article will focus more on the vision plan made for higher education and potentials risks ahead risks can be managed well only if identified correctly and at the right time the new policy is expected to bring positive and long lasting changes in the indian higher education system several innovative ideas have been considered while formulating this policy to improve effectiveness and finally achieve its long term goal there are some really great steps planned within the policy ambit for taking the indian education system to a new level of exce

In [79]:
tokenized_text =nltk.word_tokenize(cleaned_text)
tokenized_text2 =nltk.word_tokenize(cleaned_text2)

In [55]:
tokenized_text

['the',
 'new',
 'education',
 'policy',
 'has',
 'a',
 'commendable',
 'vision',
 'but',
 'its',
 'potency',
 'will',
 'depend',
 'on',
 'whether',
 'it',
 'is',
 'able',
 'to',
 'effectively',
 'integrate',
 'with',
 'the',
 'government',
 's',
 'other',
 'policy',
 'initiatives',
 'india',
 'introduced',
 'its',
 'new',
 'national',
 'education',
 'policy',
 'nep',
 'last',
 'week',
 'laying',
 'out',
 'the',
 'narendra',
 'modi',
 'government',
 's',
 'vision',
 'and',
 'broad',
 'direction',
 'conceived',
 'for',
 'educational',
 'reform',
 'it',
 'was',
 'considerably',
 'overdue',
 'the',
 'nep',
 'is',
 'only',
 'india',
 's',
 'third',
 'education',
 'policy',
 'document',
 'the',
 'previous',
 'one',
 'was',
 'revised',
 'in',
 'the',
 'policy',
 'introduces',
 'a',
 'whole',
 'gamut',
 'of',
 'changes',
 'and',
 'reads',
 'as',
 'a',
 'very',
 'progressive',
 'document',
 'overall',
 'with',
 'a',
 'firm',
 'grasp',
 'on',
 'the',
 'current',
 'socio',
 'economic',
 'landsca

In [80]:
stop_words = ["i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself",
              "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself",
              "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these",
              "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do",
              "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while",
              "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before",
              "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again",
              "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each",
              "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than",
              "too", "very", "s", "t", "can", "will", "just", "don", "should", "now","new","nep","rs"]

# Removing stop words from the tokenized words list
final_words = [word for word in tokenized_text if word not in stop_words]
final_words2 = [word for word in tokenized_text2 if word not in stop_words]

In [57]:
final_words

['education',
 'policy',
 'commendable',
 'vision',
 'potency',
 'depend',
 'whether',
 'able',
 'effectively',
 'integrate',
 'government',
 'policy',
 'initiatives',
 'india',
 'introduced',
 'national',
 'education',
 'policy',
 'last',
 'week',
 'laying',
 'narendra',
 'modi',
 'government',
 'vision',
 'broad',
 'direction',
 'conceived',
 'educational',
 'reform',
 'considerably',
 'overdue',
 'india',
 'third',
 'education',
 'policy',
 'document',
 'previous',
 'one',
 'revised',
 'policy',
 'introduces',
 'whole',
 'gamut',
 'changes',
 'reads',
 'progressive',
 'document',
 'overall',
 'firm',
 'grasp',
 'current',
 'socio',
 'economic',
 'landscape',
 'prospect',
 'future',
 'uncertainty',
 'education',
 'generation',
 'learners',
 'necessarily',
 'engage',
 'increasing',
 'dematerialisation',
 'digitalisation',
 'economies',
 'requiring',
 'completely',
 'set',
 'capabilities',
 'order',
 'able',
 'keep',
 'seems',
 'even',
 'urgent',
 'prerogative',
 'trend',
 'towards',
 

In [60]:
from sklearn.feature_extraction.text import CountVectorizer 
c_vect = CountVectorizer()
c_vect.fit(final_words)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [62]:
#vect1.fit_transform(string)
print("bag of words :",c_vect.get_feature_names())
print("vocab        :",c_vect.vocabulary_)

bag of words : ['able', 'absence', 'accelerated', 'access', 'achievement', 'acknowledge', 'acknowledging', 'across', 'adapt', 'adaptive', 'add', 'additionally', 'address', 'advantages', 'affected', 'age', 'agile', 'ai', 'already', 'also', 'among', 'analysing', 'anxiety', 'arabic', 'arguably', 'around', 'aspect', 'aspects', 'assessment', 'automation', 'availability', 'available', 'backgrounds', 'based', 'begin', 'beginning', 'behind', 'better', 'beyond', 'big', 'bilingualism', 'blended', 'brainstorm', 'break', 'brings', 'broad', 'browsing', 'building', 'capabilities', 'centred', 'certain', 'challenges', 'change', 'changes', 'changing', 'children', 'cited', 'class', 'climate', 'code', 'coding', 'coherent', 'commendable', 'communal', 'communication', 'competencies', 'competitive', 'complemented', 'completely', 'comprehending', 'computational', 'computer', 'computers', 'conceived', 'conceptual', 'conceptualisation', 'conceptualise', 'concurrent', 'considerable', 'considerably', 'considered

In [ ]:
# tokenized_text2 =nltk.word_tokenize(text2)

In [81]:
final_words2

['july',
 'going',
 'important',
 'day',
 'indian',
 'education',
 'system',
 'government',
 'decided',
 'bring',
 'national',
 'education',
 'policy',
 'long',
 'term',
 'vision',
 'making',
 'india',
 'global',
 'knowledge',
 'superpower',
 'focus',
 'inclusiveness',
 'participation',
 'holistic',
 'approach',
 'third',
 'series',
 'since',
 'independence',
 'first',
 'two',
 'introduced',
 'respectively',
 'based',
 'pillars',
 'access',
 'equity',
 'quality',
 'affordability',
 'accountability',
 'article',
 'focus',
 'vision',
 'plan',
 'made',
 'higher',
 'education',
 'potentials',
 'risks',
 'ahead',
 'risks',
 'managed',
 'well',
 'identified',
 'correctly',
 'right',
 'time',
 'policy',
 'expected',
 'bring',
 'positive',
 'long',
 'lasting',
 'changes',
 'indian',
 'higher',
 'education',
 'system',
 'several',
 'innovative',
 'ideas',
 'considered',
 'formulating',
 'policy',
 'improve',
 'effectiveness',
 'finally',
 'achieve',
 'long',
 'term',
 'goal',
 'really',
 'great

In [82]:
c_new_vect = c_vect.transform(final_words2)
print ("Text Present at ",c_new_vect.toarray())
print ("Text lenght is ",len(c_new_vect.toarray()))
# Compare with the indexes
print ("original indexes", c_vect.get_feature_names())
print ("original lenght", len(c_vect.get_feature_names()))

Text Present at  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Text lenght is  430
original indexes ['able', 'absence', 'accelerated', 'access', 'achievement', 'acknowledge', 'acknowledging', 'across', 'adapt', 'adaptive', 'add', 'additionally', 'address', 'advantages', 'affected', 'age', 'agile', 'ai', 'already', 'also', 'among', 'analysing', 'anxiety', 'arabic', 'arguably', 'around', 'aspect', 'aspects', 'assessment', 'automation', 'availability', 'available', 'backgrounds', 'based', 'begin', 'beginning', 'behind', 'better', 'beyond', 'big', 'bilingualism', 'blended', 'brainstorm', 'break', 'brings', 'broad', 'browsing', 'building', 'capabilities', 'centred', 'certain', 'challenges', 'change', 'changes', 'changing', 'children', 'cited', 'class', 'climate', 'code', 'coding', 'coherent', 'commendable', 'communal', 'communication', 'competencies', 'competitive', 'complemented', 'completely', 'comprehending', 'comp

In [83]:
import pandas as pd
df=pd.DataFrame(c_new_vect.toarray(),columns=c_vect.get_feature_names())

In [85]:
df.head(50)

able  absence  accelerated  access  ...  world  would  year  young
0      0        0            0       0  ...      0      0     0      0
1      0        0            0       0  ...      0      0     0      0
2      0        0            0       0  ...      0      0     0      0
3      0        0            0       0  ...      0      0     0      0
4      0        0            0       0  ...      0      0     0      0
5      0        0            0       0  ...      0      0     0      0
6      0        0            0       0  ...      0      0     0      0
7      0        0            0       0  ...      0      0     0      0
8      0        0            0       0  ...      0      0     0      0
9      0        0            0       0  ...      0      0     0      0
10     0        0            0       0  ...      0      0     0      0
11     0        0            0       0  ...      0      0     0      0
12     0        0            0       0  ...      0      0     0      0
13     0        0            0       0  ...      0      0     0      0
14     0        0            0       0  ...      0      0     0      0
15     0        0            0       0  ...      0      0     0      0
16     0        0            0       0  ...      0      0     0      0
17     0        0            0       0  ...      0      0     0      0
18     0        0            0       0  ...      0      0     0      0
19     0        0            0       0  ...      0      0     0      0
20     0        0            0       0  ...      0      0     0      0
21     0        0            0       0  ...      0      0     0      0
22     0        0            0       0  ...      0      0     0      0
23     0        0            0       0  ...      0      0     0      0
24     0        0            0       0  ...      0      0     0      0
25     0        0            0       0  ...      0      0     0      0
26     0        0            0       0  ...      0      0     0      0
27     0        0            0       0  ...      0      0     0      0
28     0        0            0       0  ...      0      0     0      0
29     0        0            0       0  ...      0      0     0      0
30     0        0            0       0  ...      0      0     0      0
31     0        0            0       0  ...      0      0     0      0
32     0        0            0       0  ...      0      0     0      0
33     0        0            0       0  ...      0      0     0      0
34     0        0            0       0  ...      0      0     0      0
35     0        0            0       0  ...      0      0     0      0
36     0        0            0       1  ...      0      0     0      0
37     0        0            0       0  ...      0      0     0      0
38     0        0            0       0  ...      0      0     0      0
39     0        0            0       0  ...      0      0     0      0
40     0        0            0       0  ...      0      0     0      0
41     0        0            0       0  ...      0      0     0      0
42     0        0            0       0  ...      0      0     0      0
43     0        0            0       0  ...      0      0     0      0
44     0        0            0       0  ...      0      0     0      0
45     0        0            0       0  ...      0      0     0      0
46     0        0            0       0  ...      0      0     0      0
47     0        0            0       0  ...      0      0     0      0
48     0        0            0       0  ...      0      0     0      0
49     0        0            0       0  ...      0      0     0      0

[50 rows x 543 columns]